### ISSUE TITLE
Problem: Slider support only 80%

### ISSUE THREAD

**Issue by LinoJo** [ho0ber/NK2Tray#22]
hi there,

i´ve test the last verison of release and i´ve problems with the slider.
The hardeware silder are up to 100% but the software silders in Windows are only 80% (at master).
If i change some application slider its only goes up to 62%.

Is it maybe a problem that i´m from EU?
Normaly the EU Speaker-Setting are more "powerful" (there is no/higher policy limit)..

Can someone help me?

**Comment by ReapersDragon** [comment]
My slider is not going to 80% but 99% even though the slider is at 100%

**Comment by maicomstoppa** [comment]
Download Korg Kontrol Editor Software (https://www.korg.com/us/products/computergear/nanokontrol2/) and check if the problematic slider values are set as"0 to 127". 

127 means 100% volume.

**Comment by LinoJo** [comment]
thanks, it works!!
