### ISSUE TITLE
Behringer X Touch Mini not working

### ISSUE THREAD

**Issue by jordykoppen** [ho0ber/NK2Tray#23]
I bought this device for this application, unfortunately I can't get it to work. Is there some additional software/drivers I need to install?

**Comment by LinoJo** [comment]
I'm not sure if your device is supported.
But I am not a developer of the software.
I can only say, with the Korg nanoKontrol2 you do not need additional software.

**Comment by jordykoppen** [comment]
The device is supported as it's shown in [this video](https://www.youtube.com/watch?v=Ze23ua9O7Vk)

I resolved the issue by putting the controller in MC mode. You can do this by plugging the device with the usb cable whilst holding the MC button. Maybe it should be put in the Readme?
