### ISSUE TITLE
[BUG] startindex cannot be less than zero. SYSTEM SOUND

### ISSUE THREAD

**Issue by Krextouch** [ho0ber/NK2Tray#48]
Hey,
so today i got my KORG nanoKONTROL2 to test out this project. I found out a problem that the program can not start after setting a fader to SYSTEM SOUNDS. Every restart of the program gets the message that "System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. Prametername: startIndex..."
Also the icon from the task bar disappears in about 3sec.

**To Reproduce**
Set via the task bar one fader to System Sound.
Restart your PC.
The program can not open.

**Expected behavior**
Start up

**FIXING**
Just delete your config-file.

**Screenshots**
![Error](https://user-images.githubusercontent.com/38737641/78179459-862d8000-7461-11ea-94fc-97fed104b208.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 V. 10.0.18363 Build 18363]
 - Browser [Chrome V.80.0.3987.149]

**Midi device:**
Korg NanoControl2

**Comment by jpwilliams** [comment]
https://github.com/ho0ber/NK2Tray/blob/c9a04db47aab6946a7cf6762b7f935e0300faa66/NK2Tray/Fader.cs#L142 for reference.

Either `deviceIndex` or `endIndex` there must be failing to find what they're looking for, so returning `-1`.
