### ISSUE TITLE
[BUG] System.NullReferenceException on startup

### ISSUE THREAD

**Issue by mikadiii** [ho0ber/NK2Tray#95]
**Describe the bug**
This is happening whenever I start the program
![nk2](https://user-images.githubusercontent.com/58089321/105461121-0e993d80-5c8d-11eb-9b71-348960e0ccf3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 / 20H2 / 19042.746

**Midi device:**
Korg NanoControl

**Additional context**
It was working yesterday, I did not change anything since then.
After the error occurred I restarted my pc which caused an Windows Update

**Comment by mikadiii** [comment]
It's working again

**Comment by NG-Bullseye** [comment]
Same Problem here

**Comment by Gima92** [comment]
Same problem here, windows just updated today whitout me asking like fucking always, and fucked everything. Can't open the program now, any advice on what should I do? I tried restarting comptuer, reinstalling program, plug and unplug usb , etc.
