### ISSUE TITLE
[BUG] NullReferenceException when opening

### ISSUE THREAD

**Issue by alazymeme** [ho0ber/NK2Tray#96]
**Describe the bug**
When I try to open NK2 Tray, I get the following error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at NK2Tray.SysTrayApp..ctor()
  at NK2Tray.SysTrayApp.Main()
```

**To Reproduce**
1. Open NK2 Tray

**Expected behavior**
Should open as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/106814427-1958c700-66be-11eb-9668-dcb6e906df5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 | 20H2 | Build 19042.789
 - Browser: Microsoft Edge v88.0.705.56
 - Version: 0.0.18

**Midi device:**
 - Korg NanoControl

**Additional Information:**
Potentially cause by the latest windows update, was working fine yesterday before I updated.

**Comment by PlutoPlayz** [comment]
I would just switch to MIDI-Mixer



________________________________

**Comment by alazymeme** [comment]
This somehow fixed itself, no longer having the issue. Weird
